# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "mm-n8n-state-bucket"
    use_lockfile   = true
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
